# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    
    env:
      FC: gfortran
      OMPI_FC: gfortran
      LIBACCESSOM2_ROOT: ${{ github.workspace }}/libaccessom2
      platform: ubuntu

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code 
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      
      - name: Determing OS version
        run: | 
          echo $(lsb_release -a)
          echo "os_version=$(lsb_release -a)" >> $GITHUB_ENV

      - name: Install dependencies
        run: sudo apt-get install -y csh openmpi-bin libopenmpi-dev netcdf-bin libnetcdf-dev libnetcdff-dev

      - name: Build libaccessom2
        run: |
          ls -lR
          echo Building 1 degree
          env
          ./build.sh ${platform} 
      
      - name: Prepare release
        run: |
          tar --transform 's,build,libaccessom2,' -cvf binary_release_${{ env.os_version}}.tar build/lib/ build/include/

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: binary_release_${{ env.os_version}}
          path: binary_release_${{ env.os_version}}.tar
