# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      FC: gfortran
      OMPI_FC: gfortran
      LIBACCESSOM2_ROOT: ${{ github.workspace }}/libaccessom2
      OASIS_ROOT: ${{ github.workspace }}/oasis3-mct/Linux/lib
      platform: ubuntu

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code 
        uses: actions/checkout@v2
      
      # Get OASIS dependency
      - name: Checkout OASIS3-mct
        uses: actions/checkout@v2
        with:
          repository: COSIMA/oasis3-mct
          path: oasis3-mct

      # Install dependencies
      - name: Install dependencies
        run: sudo apt-get install -y csh openmpi-bin libopenmpi-dev libopenmpi2 netcdf-bin libnetcdf-dev libnetcdff-dev libnetcdf13 

      # Compile OASIS
      - name: Compile OASIS3-mct
        run: cd ${{ github.workspace }}/oasis3-mct && make ${platform}

      # Build libaccessom2
      - name: Build libaccessom2
        run: |
          echo Building 1 degree
          env
          ./build.sh ${platform} 